slide_dir: slides
error_log: errors.txt
slide_duration: 3
transition_duration: 0.5  # Shorter transitions for Pi
fps: 20  # Lower FPS for Pi
font_size: 36  # Slightly smaller font for Pi
text_color: [255, 255, 255] # RGB tuple
footer_bg_color: [0, 0, 0, 128] # RGBA tuple
error_retry_delay: 30
qr_box_size: 4  # Smaller QR code for Pi
qr_border: 2
available_transitions: [fade, slide]  # Only fast transitions for Pi
# Performance optimization settings for Raspberry Pi
transition_fps: 10  # Very low FPS for smooth transitions on Pi
use_fast_transitions: true  # Use simplified transitions for Pi performance
